name: frigate
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: 0.14.1
version: 1.0.3
description: Frigate NVR Helm Chart
type: application
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/frigate
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - frigate
  - nvr
  - security
  - cameras
sources:
  - https://github.com/blakeblackshear/frigate
