{{- if .Values.jellyfin.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: {{ .Release.Name }}-jellyfin
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  strategy:
    type: Recreate
  replicas: {{ .Values.jellyfin.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: jellyfin
      app.kubernetes.io/instance: {{ .Release.Name }}-jellyfin
  template:
    metadata:
      labels:
        app.kubernetes.io/name: jellyfin
        app.kubernetes.io/instance: {{ .Release.Name }}-jellyfin
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    spec:
    {{- if .Values.jellyfin.enableDLNA }}
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
    {{- end }}
      containers:
        - name: {{ .Release.Name }}
          image: "{{ .Values.jellyfin.image.repository }}:{{ .Values.jellyfin.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.jellyfin.image.pullPolicy }}
        {{ if .Values.jellyfin.extraEnvVars }}
          env:
            {{- toYaml .Values.jellyfin.extraEnvVars | nindent 12 }}
        {{- end }}
        {{ if .Values.jellyfin.securityContext }}
          securityContext:
            {{- toYaml .Values.jellyfin.securityContext | nindent 12 }}
        {{- end }}
          ports:
            - name: http
              containerPort: {{ .Values.jellyfin.service.port }}
              protocol: TCP
          {{ if .Values.jellyfin.enableDLNA }}
            - name: dlna
              containerPort: 1900
              hostPort: 1900
              protocol: UDP
          {{- end }}
        {{ if .Values.jellyfin.livenessProbe.enabled }}
          livenessProbe:
          {{ if .Values.jellyfin.livenessProbe.initialDelaySeconds }}
            initialDelaySeconds: {{ .Values.jellyfin.livenessProbe.initialDelaySeconds }}
          {{- end }}
          {{ if .Values.jellyfin.livenessProbe.periodSeconds }}
            periodSeconds: {{ .Values.jellyfin.livenessProbe.periodSeconds }}
          {{- end }}
          {{ if .Values.jellyfin.livenessProbe.timeoutSeconds }}
            timeoutSeconds: {{ .Values.jellyfin.livenessProbe.timeoutSeconds }}
          {{- end }}
          {{ if .Values.jellyfin.livenessProbe.failureThreshold }}
            failureThreshold: {{ .Values.jellyfin.livenessProbe.failureThreshold }}
          {{- end }}
          {{ if .Values.jellyfin.livenessProbe.successThreshold }}
            successThreshold: {{ .Values.jellyfin.livenessProbe.successThreshold }}
          {{- end }}
            tcpSocket:
              port: http
        {{- end }}
        {{ if .Values.jellyfin.readinessProbe.enabled }}
          readinessProbe:
          {{ if .Values.jellyfin.readinessProbe.initialDelaySeconds }}
            initialDelaySeconds: {{ .Values.jellyfin.readinessProbe.initialDelaySeconds }}
          {{- end }}
          {{ if .Values.jellyfin.readinessProbe.periodSeconds }}
            periodSeconds: {{ .Values.jellyfin.readinessProbe.periodSeconds }}
          {{- end }}
          {{ if .Values.jellyfin.readinessProbe.timeoutSeconds }}
            timeoutSeconds: {{ .Values.jellyfin.readinessProbe.timeoutSeconds }}
          {{- end }}
          {{ if .Values.jellyfin.readinessProbe.failureThreshold }}
            failureThreshold: {{ .Values.jellyfin.readinessProbe.failureThreshold }}
          {{- end }}
          {{ if .Values.jellyfin.readinessProbe.successThreshold }}
            successThreshold: {{ .Values.jellyfin.readinessProbe.successThreshold }}
          {{- end }}
            tcpSocket:
              port: http
        {{- end }}
          volumeMounts:
            - mountPath: /config
              name: config
            {{- range .Values.jellyfin.persistence.extraExistingClaimMounts }}
            - name: {{ .name }}
              mountPath: {{ .mountPath }}
              readOnly: {{ .readOnly }}
            {{- end }}
            {{- if .Values.jellyfin.extraVolumeMounts }}
            {{- toYaml .Values.jellyfin.extraVolumeMounts | nindent 12 }}
            {{- end }}
            {{- if and .Values.sonarr.enabled .Values.sonarr.persistence.enabled }}
            - mountPath: "/media/{{ .Values.media.paths.tv }}"
              name: media
              subPath: {{ .Values.media.paths.tv }}
            {{- end }}
            {{- if and .Values.radarr.enabled .Values.radarr.persistence.enabled }}
            - mountPath: "/media/{{ .Values.media.paths.movies }}"
              name: media
              subPath: {{ .Values.media.paths.movies }}
            {{- end }}
            {{- if and .Values.lidarr.enabled .Values.lidarr.persistence.enabled }}
            - mountPath: "/media/{{ .Values.media.paths.music }}"
              name: media
              subPath: {{ .Values.media.paths.music }}
            {{- end }}
          {{- if .Values.jellyfin.extraContainers }}
          {{- toYaml .Values.jellyfin.extraContainers | nindent 8 }}
          {{- end }}
          resources:
{{ toYaml .Values.jellyfin.resources | indent 12 }}
          terminationMessagePolicy: FallbackToLogsOnError
          securityContext: {{- toYaml .Values.jellyfin.securityContext | nindent 12 }}
  {{- if .Values.jellyfin.extraInitContainers }}
      initContainers:
      {{- toYaml .Values.jellyfin.extraInitContainers | nindent 10 }}
  {{- end }}
      volumes:
      - name: config
      {{- if .Values.jellyfin.persistence.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.jellyfin.persistence.existingClaim }}{{ .Values.jellyfin.persistence.existingClaim }}{{- else }}{{ .Release.Name }}-jellyfin{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      - name: media
      {{- if .Values.media.enabled }}
        persistentVolumeClaim:
          claimName: {{ if .Values.media.existingClaim }}{{ .Values.media.existingClaim }}{{- else }}{{ .Release.Name }}-media{{- end }}
      {{- else }}
        emptyDir: {}
      {{- end }}
      {{- range .Values.jellyfin.persistence.extraExistingClaimMounts }}
      - name: {{ .name }}
        persistentVolumeClaim:
          claimName: {{ .existingClaim }}
      {{- end }}
      {{- if .Values.jellyfin.extraVolumes }}
      {{- toYaml .Values.jellyfin.extraVolumes | nindent 6 }}
      {{- end }}
    {{- with .Values.jellyfin.nodeSelector }}
      nodeSelector:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.jellyfin.affinity }}
      affinity:
{{ toYaml . | indent 8 }}
    {{- end }}
    {{- with .Values.jellyfin.tolerations }}
      tolerations:
{{ toYaml . | indent 8 }}
    {{- end }}
      securityContext: {{- toYaml .Values.jellyfin.podSecurityContext | nindent 8 }}
{{- end }}
