{{- if and .Values.jellyfin.enabled .Values.jellyfin.ingress.enabled }}
{{- if and .Values.authelia.enabled .Values.authelia.autoConfigureApps .Values.authelia.ingress.hosts }}
  {{- if eq .Values.authelia.ingressController "nginx" }}
    {{- $_ := set .Values.jellyfin.ingress.annotations "nginx.ingress.kubernetes.io/auth-url" (printf "http://%s-authelia.%s.svc.cluster.local:9091/api/verify" .Release.Name .Release.Namespace) }}
    {{- $_ := set .Values.jellyfin.ingress.annotations "nginx.ingress.kubernetes.io/auth-signin" (printf "https://%s/api/auth/signin?rm=$request_method" (index .Values.authelia.ingress.hosts 0).host) }}
  {{- else if eq .Values.authelia.ingressController "traefik" }}
    {{- $_ := set .Values.jellyfin.ingress.annotations "traefik.ingress.kubernetes.io/router.middlewares" (printf "%s-authelia-auth@kubernetescrd" .Release.Namespace) }}
  {{- end }}
{{- end }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Release.Name }}-jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: {{ .Release.Name }}-jellyfin
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    {{- with .Values.jellyfin.ingress.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
{{- with .Values.jellyfin.ingress.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
{{- end }}
spec:
  {{- if or (.Capabilities.APIVersions.Has "networking.k8s.io/v1/IngressClass") (.Capabilities.APIVersions.Has "networking.k8s.io/v1beta1/IngressClass") }}
  {{- if .Values.jellyfin.ingress.ingressClassName }}
  ingressClassName: {{ .Values.jellyfin.ingress.ingressClassName }}
  {{- end }}
  {{- end }}
{{- if .Values.jellyfin.ingress.tls }}
  tls:
  {{- range .Values.jellyfin.ingress.tls }}
    - hosts:
      {{- range .hosts }}
        - {{ . | quote }}
      {{- end }}
      secretName: {{ .secretName }}
  {{- end }}
{{- end }}
  rules:
  {{- range .Values.jellyfin.ingress.hosts }}
    - host: {{ . | quote }}
      http:
        paths:
          - pathType: Prefix
            path: {{ $.Values.jellyfin.ingress.path }}
            backend:
              service:
                name: {{ $.Release.Name }}-jellyfin
                port:
                  name: http
  {{- end }}
{{- end }}
