{{- if and .Values.jellyfin.enabled .Values.jellyfin.persistence.config.enabled (not .Values.jellyfin.persistence.config.existingClaim) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-jellyfin
  labels:
    app.kubernetes.io/name: jellyfin
    app.kubernetes.io/instance: {{ .Release.Name }}-jellyfin
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
  {{- with .Values.jellyfin.persistence.config.labels }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.jellyfin.persistence.config.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ .Values.jellyfin.persistence.config.accessMode | quote }}
  resources:
    requests:
      storage: {{ .Values.jellyfin.persistence.config.size | quote }}
  {{- if .Values.jellyfin.persistence.config.storageClass }}
  {{- if (eq "-" .Values.jellyfin.persistence.config.storageClass) }}
  storageClassName: ""
  {{- else }}
  storageClassName: "{{ .Values.jellyfin.persistence.config.storageClass }}"
  {{- end }}
  {{- end }}
{{- end }}
