{{- if index .Values "home-assistant" "enabled" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  {{- if not (index .Values "home-assistant" "autoscaling" "enabled") }}
  replicas: {{ index .Values "home-assistant" "replicaCount" }}
  {{- end }}
  strategy:
    {{- index .Values "home-assistant" "deployment" "strategy" | toYaml | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: home-assistant
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with index .Values "home-assistant" "podAnnotations" }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: home-assistant
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    spec:
      {{- with index .Values "home-assistant" "imagePullSecrets" }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ (index .Values "home-assistant" "serviceAccount" "name") | default (printf "%s-home-assistant" .Release.Name) }}
      securityContext:
        {{- toYaml (index .Values "home-assistant" "podSecurityContext") | nindent 8 }}
      {{- if index .Values "home-assistant" "initContainers" }}
      initContainers:
        {{- toYaml (index .Values "home-assistant" "initContainers") | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          {{- if index .Values "home-assistant" "persistence" "enabled" }}
          persistentVolumeClaim:
            claimName: {{ (index .Values "home-assistant" "persistence" "existingClaim") | default (printf "%s-home-assistant" .Release.Name) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if index .Values "home-assistant" "persistence" "additionalVolumes" }}
          {{- index .Values "home-assistant" "persistence" "additionalVolumes" | toYaml | nindent 8}}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml (index .Values "home-assistant" "securityContext") | nindent 12 }}
          image: "{{ index .Values "home-assistant" "image" "repository" }}:{{ (index .Values "home-assistant" "image" "tag") | default .Chart.AppVersion }}"
          imagePullPolicy: {{ index .Values "home-assistant" "image" "pullPolicy" }}
          volumeMounts:
            - mountPath: /config
              name: config
          {{- if index .Values "home-assistant" "persistence" "additionalMounts" }}
            {{- index .Values "home-assistant" "persistence" "additionalMounts" | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8123
              protocol: TCP
          env:
            {{- range $k,$v := index .Values "home-assistant" "env" }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml (index .Values "home-assistant" "resources") | nindent 12 }}
      {{- with index .Values "home-assistant" "nodeSelector" }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with index .Values "home-assistant" "affinity" }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with index .Values "home-assistant" "tolerations" }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
