{{- if and (index .Values "home-assistant" "enabled") (index .Values "home-assistant" "autoscaling" "enabled") }}
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-home-assistant
  minReplicas: {{ index .Values "home-assistant" "autoscaling" "minReplicas" }}
  maxReplicas: {{ index .Values "home-assistant" "autoscaling" "maxReplicas" }}
  metrics:
    {{- if index .Values "home-assistant" "autoscaling" "targetCPUUtilizationPercentage" }}
    - type: Resource
      resource:
        name: cpu
        targetAverageUtilization: {{ index .Values "home-assistant" "autoscaling" "targetCPUUtilizationPercentage" }}
    {{- end }}
    {{- if index .Values "home-assistant" "autoscaling" "targetMemoryUtilizationPercentage" }}
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: {{ index .Values "home-assistant" "autoscaling" "targetMemoryUtilizationPercentage" }}
    {{- end }}
{{- end }}
