{{- if and (index .Values "home-assistant" "enabled") (index .Values "home-assistant" "persistence" "enabled") (not (index .Values "home-assistant" "persistence" "existingClaim")) }}
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Release.Name }}-home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- if index .Values "home-assistant" "persistence" "annotations" }}
  annotations:
    {{- toYaml (index .Values "home-assistant" "persistence" "annotations") | nindent 4 }}
  {{- end }}
spec:
  accessModes:
    - {{ index .Values "home-assistant" "persistence" "accessMode" | quote }}
  {{- if index .Values "home-assistant" "persistence" "storageClass" }}
  storageClassName: {{ index .Values "home-assistant" "persistence" "storageClass" | quote }}
  {{- end }}
  resources:
    requests:
      storage: {{ index .Values "home-assistant" "persistence" "size" | quote }}
{{- end }}
