{{- if and (index .Values "home-assistant" "enabled") (index .Values "home-assistant" "serviceAccount" "create") }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}-home-assistant
  labels:
    app.kubernetes.io/name: home-assistant
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
  {{- with index .Values "home-assistant" "serviceAccount" "annotations" }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
