{{- if .Values.emby.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-emby
  labels:
    app.kubernetes.io/name: emby
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  {{- if not .Values.emby.autoscaling.enabled }}
  replicas: {{ .Values.emby.replicaCount }}
  {{- end }}
  strategy:
    {{- .Values.emby.deployment.strategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: emby
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.emby.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: emby
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    spec:
      {{- with .Values.emby.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.emby.serviceAccount.name | default (printf "%s-emby" .Release.Name) }}
      securityContext:
        {{- toYaml .Values.emby.podSecurityContext | nindent 8 }}
      {{- if .Values.emby.initContainers }}
      initContainers:
        {{- toYaml .Values.emby.initContainers | nindent 8 }}
      {{- end }}
      volumes:
        - name: config
          {{- if .Values.emby.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.emby.persistence.existingClaim | default (printf "%s-emby" .Release.Name) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: media
          {{- if and .Values.jellyfin.enabled .Values.jellyfin.persistence.media.enabled .Values.emby.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.jellyfin.persistence.media.existingClaim }}{{ .Values.jellyfin.persistence.media.existingClaim }}{{- else }}{{ .Release.Name }}-jellyfin-media{{- end }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.emby.persistence.additionalVolumes }}
          {{- .Values.emby.persistence.additionalVolumes | toYaml | nindent 8}}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.emby.securityContext | nindent 12 }}
          image: "{{ .Values.emby.image.repository }}:{{ .Values.emby.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.emby.image.pullPolicy }}
          volumeMounts:
            - mountPath: /config
              name: config
          {{- if and .Values.jellyfin.enabled .Values.jellyfin.persistence.media.enabled .Values.sonarr.persistence.enabled .Values.emby.persistence.enabled }}
            - mountPath: "/media/{{ .Values.sonarr.persistence.path }}"
              name: media
              subPath: {{ .Values.sonarr.persistence.path }}
          {{- end }}
          {{- if and .Values.jellyfin.enabled .Values.jellyfin.persistence.media.enabled .Values.radarr.persistence.enabled .Values.emby.persistence.enabled }}
            - mountPath: "/media/{{ .Values.radarr.persistence.path }}"
              name: media
              subPath: {{ .Values.radarr.persistence.path }}
          {{- end }}
          {{- if and .Values.jellyfin.enabled .Values.jellyfin.persistence.media.enabled .Values.lidarr.persistence.enabled .Values.emby.persistence.enabled }}
            - mountPath: "/media/{{ .Values.lidarr.persistence.path }}"
              name: media
              subPath: {{ .Values.lidarr.persistence.path }}
          {{- end }}
          {{- if .Values.emby.persistence.additionalMounts }}
            {{- .Values.emby.persistence.additionalMounts | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 8096
              protocol: TCP
          env:
            {{- range $k,$v := .Values.emby.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.emby.resources | nindent 12 }}
      {{- with .Values.emby.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.emby.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.emby.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
