{{- if .Values.emby.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-emby
  labels:
    app.kubernetes.io/name: emby
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  type: {{ .Values.emby.service.type | default "ClusterIP" }}
  ports:
    - port: {{ .Values.emby.service.port | default 8096 }}
      targetPort: http
      protocol: TCP
      name: http
{{ if (and (eq .Values.emby.service.type "NodePort") (not (empty .Values.emby.service.nodePort))) }}
      nodePort: {{.Values.emby.service.nodePort}}
{{ end }}
  selector:
    app.kubernetes.io/name: emby
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end }}
