name: excalidraw
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: 0.17.6
version: 1.0.2
description: Raul Excalidraw Helm Chart
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/excalidraw
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - excalidraw
  - diagrams
  - design
sources:
  - https://github.com/excalidraw/excalidraw
