name: servarr
maintainers:
  - name: kubitodev
    url: https://kubito.dev
apiVersion: v2
appVersion: 1.2.2
version: 1.2.2
description: Kubito Servarr Helm Chart
home: https://github.com/kubitodev/helm/tree/main/charts/servarr
icon: https://kubito.dev/images/kubito.svg
keywords:
  - kubernetes
  - bazarr
  - lidarr
  - sonarr
  - radarr
  - flaresolverr
  - jellyfin
  - jellyseerr
  - qbittorrent
  - prowlarr
  - cleanuparr
  - sabnzbd
  - mealie
  - frigate
  - vaultwarden
  - plex
  - emby
  - immich
  - nextcloud
  - home-assistant
sources:
  - https://github.com/Servarr
