name: servarr
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: 1.2.2
version: 1.0.6
description: Raul Servarr Helm Chart
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/servarr
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - bazarr
  - lidarr
  - sonarr
  - radarr
  - flaresolverr
  - jellyfin
  - jellyseerr
  - qbittorrent
  - prowlarr
  - cleanuparr
  - sabnzbd
  - frigate
  - plex
  - emby
sources:
  - https://github.com/Servarr
