name: mealie
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: v2.2.0
version: 1.0.2
description: Mealie Helm Chart
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/mealie
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - mealie
  - recipes
  - cookbook
sources:
  - https://github.com/mealie-recipes/mealie
