name: penpot
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: 2.2.1
version: 1.0.2
description: Raul Penpot Helm Chart
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/penpot
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - penpot
  - penpotapp
  - design
sources:
  - https://github.com/penpot/penpot

dependencies:
  - condition: global.postgresqlEnabled
    name: postgresql
    repository: https://charts.bitnami.com/bitnami
    version: 15.x.x
  - condition: global.redisEnabled
    name: redis
    repository: https://charts.bitnami.com/bitnami
    version: 18.x.x
