name: traefik-cloudflared-source-ip
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: 2.10.7
version: 1.0.11
description: Raul Traefik Cloudflared (Argo Tunnel) Real IP Helm Chart
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/traefik-cloudflared-source-ip
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - cloudflare
  - cloudflared
  - middleware
  - real-ip
  - source-ip
  - argo-tunnel
  - argo
  - traefik
sources:
  - https://github.com/raulpatel/traefik-cloudflared-source-ip

dependencies:
  - condition: global.cloudflaredEnabled
    name: cloudflared
    repository: https://charts.raulpatel.com
    # https://github.com/Masterminds/semver#checking-version-constraints
    version: 1.x.x
  - condition: global.traefikEnabled
    name: traefik
    repository: https://traefik.github.io/charts
    version: 26.0.0
