name: traefik-whitelist-ddns
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: 2.x.x
version: 1.0.5
description: Raul Traefik Whitelist DDNS Helm Chart
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/traefik-whitelist-ddns
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - traefik
  - ddns
  - cronjob
  - middleware
  - ip
  - whitelist
sources:
  - https://github.com/raulpatel/traefik-whitelist-ddns
