name: cloudflare-tunnel
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: 2025.9.1
version: 1.0.3
description: Raul Cloudflared Tunnel Helm Chart
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/cloudflared
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - cloudflare
  - cloudflared
  - tunnel
sources:
  - https://github.com/cloudflare/cloudflared
