{{- if .Values.vaultwarden.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-vaultwarden
  labels:
    app.kubernetes.io/name: vaultwarden
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  {{- if not .Values.vaultwarden.autoscaling.enabled }}
  replicas: {{ .Values.vaultwarden.replicaCount }}
  {{- end }}
  strategy:
    {{- .Values.vaultwarden.deployment.strategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: vaultwarden
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.vaultwarden.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: vaultwarden
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    spec:
      {{- with .Values.vaultwarden.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.vaultwarden.serviceAccount.name | default (printf "%s-vaultwarden" .Release.Name) }}
      securityContext:
        {{- toYaml .Values.vaultwarden.podSecurityContext | nindent 8 }}
      {{- if .Values.vaultwarden.initContainers }}
      initContainers:
        {{- toYaml .Values.vaultwarden.initContainers | nindent 8 }}
      {{- end }}
      volumes:
        - name: data
          {{- if .Values.vaultwarden.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.vaultwarden.persistence.existingClaim | default (printf "%s-vaultwarden" .Release.Name) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.vaultwarden.persistence.additionalVolumes }}
          {{- .Values.vaultwarden.persistence.additionalVolumes | toYaml | nindent 8}}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.vaultwarden.securityContext | nindent 12 }}
          image: "{{ .Values.vaultwarden.image.repository }}:{{ .Values.vaultwarden.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.vaultwarden.image.pullPolicy }}
          volumeMounts:
            - mountPath: /data
              name: data
          {{- if .Values.vaultwarden.persistence.additionalMounts }}
            {{- .Values.vaultwarden.persistence.additionalMounts | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          env:
            {{- range $k,$v := .Values.vaultwarden.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.vaultwarden.resources | nindent 12 }}
      {{- with .Values.vaultwarden.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vaultwarden.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.vaultwarden.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
