{{- if .Values.bazarr.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-bazarr
  labels:
    app.kubernetes.io/name: bazarr
    app.kubernetes.io/instance: {{ .Release.Name }}-bazarr
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io/part-of: {{ .Release.Name | quote }}
spec:
  {{- if not .Values.bazarr.autoscaling.enabled }}
  replicas: {{ .Values.bazarr.replicaCount }}
  {{- end }}
  strategy:
    {{- .Values.bazarr.deployment.strategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: bazarr
      app.kubernetes.io/instance: {{ .Release.Name }}-bazarr
  template:
    metadata:
      {{- with .Values.bazarr.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: bazarr
        app.kubernetes.io/instance: {{ .Release.Name }}-bazarr
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
        app.kubernetes.io/part-of: {{ .Release.Name | quote }}
    spec:
      {{- with .Values.bazarr.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.bazarr.serviceAccount.name | default (printf "%s-bazarr" .Release.Name) }}
      securityContext:
        {{- toYaml .Values.bazarr.podSecurityContext | nindent 8 }}
      {{- if and .Values.media.enabled .Values.bazarr.persistence.enabled }}
      initContainers:
        - name: init-directories
          image: busybox
          command: ['sh', '-c', 'mkdir -p /media/{{ .Values.media.paths.tv }} /media/{{ .Values.media.paths.movies }} && chown -R 1000:1000 /media/{{ .Values.media.paths.tv }} /media/{{ .Values.media.paths.movies }}']
          volumeMounts:
            - name: media
              mountPath: /media
      {{- if .Values.bazarr.initContainers }}
        {{- toYaml .Values.bazarr.initContainers | nindent 8 }}
      {{- end }}
      {{- end }}
      volumes:
        - name: config
          {{- if .Values.bazarr.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.bazarr.persistence.existingClaim | default (printf "%s-bazarr" .Release.Name) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        - name: media
          {{- if and .Values.media.enabled .Values.bazarr.persistence.enabled }}
          persistentVolumeClaim:
            claimName: {{ if .Values.media.existingClaim }}{{ .Values.media.existingClaim }}{{- else }}{{ .Release.Name }}-media{{- end }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.bazarr.persistence.additionalVolumes }}
          {{- .Values.bazarr.persistence.additionalVolumes | toYaml | nindent 8}}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.bazarr.securityContext | nindent 12 }}
          image: "{{ .Values.bazarr.image.repository }}:{{ .Values.bazarr.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.bazarr.image.pullPolicy }}
          volumeMounts:
            - mountPath: /config
              name: config
          {{- if and .Values.media.enabled .Values.sonarr.persistence.enabled .Values.bazarr.persistence.enabled }}
            - mountPath: "/media/{{ .Values.media.paths.tv }}"
              name: media
              subPath: {{ .Values.media.paths.tv }}
          {{- end }}
          {{- if and .Values.media.enabled .Values.radarr.persistence.enabled .Values.bazarr.persistence.enabled }}
            - mountPath: "/media/{{ .Values.media.paths.movies }}"
              name: media
              subPath: {{ .Values.media.paths.movies }}
          {{- end }}
          {{- if .Values.bazarr.persistence.additionalMounts }}
            {{- .Values.bazarr.persistence.additionalMounts | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 6767
              protocol: TCP
          env:
            {{- range $k,$v := .Values.bazarr.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.bazarr.resources | nindent 12 }}
      {{- with .Values.bazarr.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bazarr.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.bazarr.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}