{{- if .Values.immich.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-immich
  labels:
    app.kubernetes.io/name: immich
    app.kubernetes.io/instance: {{ .Release.Name | quote }}
    app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
spec:
  {{- if not .Values.immich.autoscaling.enabled }}
  replicas: {{ .Values.immich.replicaCount }}
  {{- end }}
  strategy:
    {{- .Values.immich.deployment.strategy | toYaml | nindent 4 }}
  selector:
    matchLabels:
      app.kubernetes.io/name: immich
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      {{- with .Values.immich.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        app.kubernetes.io/name: immich
        app.kubernetes.io/instance: {{ .Release.Name | quote }}
        app.kubernetes.io/version: {{ .Chart.AppVersion | quote }}
        app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    spec:
      {{- with .Values.immich.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.immich.serviceAccount.name | default (printf "%s-immich" .Release.Name) }}
      securityContext:
        {{- toYaml .Values.immich.podSecurityContext | nindent 8 }}
      {{- if .Values.immich.initContainers }}
      initContainers:
        {{- toYaml .Values.immich.initContainers | nindent 8 }}
      {{- end }}
      volumes:
        - name: library
          {{- if .Values.immich.persistence.library.enabled }}
          persistentVolumeClaim:
            claimName: {{ .Values.immich.persistence.library.existingClaim | default (printf "%s-immich-library" .Release.Name) }}
          {{- else }}
          emptyDir: { }
          {{- end }}
        {{- if .Values.immich.persistence.additionalVolumes }}
          {{- .Values.immich.persistence.additionalVolumes | toYaml | nindent 8}}
        {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.immich.securityContext | nindent 12 }}
          image: "{{ .Values.immich.image.repository }}:{{ .Values.immich.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.immich.image.pullPolicy }}
          volumeMounts:
            - mountPath: /usr/src/app/upload
              name: library
          {{- if .Values.immich.persistence.additionalMounts }}
            {{- .Values.immich.persistence.additionalMounts | toYaml | nindent 12 }}
          {{- end }}
          ports:
            - name: http
              containerPort: 2283
              protocol: TCP
          env:
            {{- range $k,$v := .Values.immich.env }}
            - name: {{ $k }}
              value: {{ $v | quote }}
            {{- end }}
          resources:
            {{- toYaml .Values.immich.resources | nindent 12 }}
      {{- with .Values.immich.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.immich.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.immich.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
