apiVersion: v2
name: immich
description: A Helm chart for Immich - High performance self-hosted photo and video management solution
type: application
version: 1.0.4
appVersion: "1.0"
keywords:
  - immich
  - photos
  - videos
  - media
  - self-hosted
home: https://immich.app
sources:
  - https://github.com/immich-app/immich
maintainers:
  - name: FeLiNa22
