name: home-assistant
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: 2024.11.3
version: 1.0.3
description: Home Assistant Helm Chart
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/home-assistant
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - home-assistant
  - smart-home
  - automation
sources:
  - https://github.com/home-assistant/core
