name: searxng
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: 1.0.1
version: 1.0.2
description: Raul SearXNG Helm Chart
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/searxng
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - searxng
  - metasearch
  - search
  - privacy
sources:
  - https://github.com/searxng/searxng
