name: vaultwarden
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: 1.32.4
version: 1.0.2
description: Vaultwarden Helm Chart
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/vaultwarden
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - vaultwarden
  - bitwarden
  - password-manager
sources:
  - https://github.com/dani-garcia/vaultwarden
