name: kubernetes-cloudflare-ddns
maintainers:
  - name: raulpatel
    url: https://raulpatel.com
apiVersion: v2
appVersion: 1.0.1
version: 1.0.6
description: Raul Kubernetes Cloudflare DDNS Helm Chart
home: https://github.com/FeLiNa22/homeserver/tree/main/charts/kubernetes-cloudflare-ddns
icon: https://raulpatel.com/images/raul.svg
keywords:
  - kubernetes
  - cloudflare
  - ddns
  - cronjob
sources:
  - https://github.com/raulpatel/kubernetes-cloudflare-ddns
